"""Application constants."""

# Session timing
SESSION_DURATION_SECONDS = 3600  # 1 hour AWS SSO session
CHECK_INTERVAL_SECONDS = 30  # Check every 30 seconds
RENEWAL_THRESHOLD_PERCENT = 0.5  # Renew at 50% elapsed (30 minutes)
RENEWAL_THRESHOLD_SECONDS = (
    SESSION_DURATION_SECONDS * RENEWAL_THRESHOLD_PERCENT
)  # 1800 seconds

# Classification budgets
CLASSIFIER_MAX_TOKENS_PER_SAMPLE = 64
CLASSIFIER_MAX_SAMPLES_PER_STREAM = 768
CLASSIFIER_MAX_STREAMS = 3
CLASSIFIER_BYTES_PER_TOKEN_ESTIMATE = 1
CLASSIFIER_MEMORY_KIB_PER_STREAM = (
    CLASSIFIER_MAX_TOKENS_PER_SAMPLE
    * CLASSIFIER_MAX_SAMPLES_PER_STREAM
    * CLASSIFIER_BYTES_PER_TOKEN_ESTIMATE
    / 1024
)  # 48 KiB per stream
CLASSIFIER_MEMORY_MIB_TOTAL = (
    CLASSIFIER_MEMORY_KIB_PER_STREAM * CLASSIFIER_MAX_STREAMS / 1024
)  # 0.140625 MiB total across 3 streams

# Profile limits
MAX_PROFILES_IN_ROOT_MENU = 40
MAX_SUBMENU_PROFILES = 20
MAX_TOTAL_PROFILES = 100

# UI timing
TOOLTIP_THROTTLE_SECONDS = 5
TOOLTIP_THROTTLE_MS = TOOLTIP_THROTTLE_SECONDS * 1000  # 5000 ms
STATUS_WINDOW_REFRESH_MS = 1000  # 1 second
HEARTBEAT_TIMEOUT_SECONDS = 300  # 5 minutes
LOGIN_LOCK_SECONDS = 300  # 5 minutes
SSO_LOGIN_TIMEOUT_SECONDS = 180  # 3 minutes
TRAY_HOST_FAILURE_THRESHOLD = 3
PROFILE_MENU_LIMIT = MAX_PROFILES_IN_ROOT_MENU

# Tray host detection
TRAY_HOST_DETECTION_TIMEOUT_MS = 5000
